// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: favorites.sql

package streamingdb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addFavorite = `-- name: AddFavorite :exec
INSERT INTO favorites (user_id, stream_id)
VALUES ($1::uuid, $2::uuid)
ON CONFLICT DO NOTHING
`

type AddFavoriteParams struct {
	UserID   pgtype.UUID
	StreamID pgtype.UUID
}

// Ajout idempotent : un favori déjà présent ne lève pas d'erreur.
func (q *Queries) AddFavorite(ctx context.Context, arg AddFavoriteParams) error {
	_, err := q.db.Exec(ctx, addFavorite, arg.UserID, arg.StreamID)
	return err
}

const listFavoritesByUser = `-- name: ListFavoritesByUser :many
SELECT s.id::text AS id, s.user_id::text AS user_id, s.title, s.description, s.category,
       s.status, s.is_public, s.started_at, s.ended_at, s.created_at, s.updated_at,
       u.username AS broadcaster_username
FROM favorites f
JOIN streams s ON s.id = f.stream_id
JOIN users u ON u.id = s.user_id
WHERE f.user_id = $1::uuid
  AND s.archived_at IS NULL
  AND (s.is_public = true OR s.user_id = $1::uuid)
ORDER BY f.created_at DESC
`

type ListFavoritesByUserRow struct {
	ID                  string
	UserID              string
	Title               string
	Description         pgtype.Text
	Category            pgtype.Text
	Status              string
	IsPublic            bool
	StartedAt           *time.Time
	EndedAt             *time.Time
	CreatedAt           time.Time
	UpdatedAt           time.Time
	BroadcasterUsername string
}

// Flux favoris de l'utilisateur, tous statuts, non archivés. On ne renvoie que
// les flux encore visibles pour le demandeur (publics, ou lui appartenant) : un
// flux passé en privé par un tiers après coup disparaît de la liste. Le
// stream_key n'est jamais exposé ici. Trié par date d'ajout du favori (desc).
func (q *Queries) ListFavoritesByUser(ctx context.Context, userID pgtype.UUID) ([]ListFavoritesByUserRow, error) {
	rows, err := q.db.Query(ctx, listFavoritesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFavoritesByUserRow
	for rows.Next() {
		var i ListFavoritesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.Status,
			&i.IsPublic,
			&i.StartedAt,
			&i.EndedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BroadcasterUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFavorite = `-- name: RemoveFavorite :exec
DELETE FROM favorites
WHERE user_id = $1::uuid AND stream_id = $2::uuid
`

type RemoveFavoriteParams struct {
	UserID   pgtype.UUID
	StreamID pgtype.UUID
}

// Suppression idempotente : aucun effet si le favori n'existe pas.
func (q *Queries) RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) error {
	_, err := q.db.Exec(ctx, removeFavorite, arg.UserID, arg.StreamID)
	return err
}
