// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: streams.sql

package streamingdb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveStream = `-- name: ArchiveStream :one
UPDATE streams
SET archived_at = NOW(),
    updated_at = NOW(),
    status = CASE WHEN status = 'live' THEN 'ended' ELSE status END
WHERE id = $1::uuid AND user_id = $2::uuid AND archived_at IS NULL
RETURNING id::text AS id
`

type ArchiveStreamParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

// Soft delete. Si le flux était en direct, on le termine (status -> ended) pour
// ne pas laisser de ligne archivée « live » (cf. garde un-seul-live).
func (q *Queries) ArchiveStream(ctx context.Context, arg ArchiveStreamParams) (string, error) {
	row := q.db.QueryRow(ctx, archiveStream, arg.ID, arg.UserID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createStream = `-- name: CreateStream :one
INSERT INTO streams (user_id, title, description, category, status, is_public, stream_key)
VALUES (
    $1::uuid,
    $2::text,
    $3::text,
    $4::text,
    $5::text,
    $6::boolean,
    $7::text
)
RETURNING id::text AS id, user_id::text AS user_id, title, description, category,
          status, is_public, stream_key, created_at, updated_at
`

type CreateStreamParams struct {
	UserID      pgtype.UUID
	Title       string
	Description pgtype.Text
	Category    pgtype.Text
	Status      string
	IsPublic    bool
	StreamKey   string
}

type CreateStreamRow struct {
	ID          string
	UserID      string
	Title       string
	Description pgtype.Text
	Category    pgtype.Text
	Status      string
	IsPublic    bool
	StreamKey   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateStream(ctx context.Context, arg CreateStreamParams) (CreateStreamRow, error) {
	row := q.db.QueryRow(ctx, createStream,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.Status,
		arg.IsPublic,
		arg.StreamKey,
	)
	var i CreateStreamRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Status,
		&i.IsPublic,
		&i.StreamKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const endOrphanLiveStreams = `-- name: EndOrphanLiveStreams :execrows
UPDATE streams
SET status = 'ended', ended_at = NOW(), updated_at = NOW()
WHERE status = 'live' AND archived_at IS NULL
`

// Réconciliation au démarrage : les sessions LiveSessions sont en mémoire et
// reparties vides après un redémarrage ; on termine les flux restés 'live' en
// base (orphelins sans session ni audio).
func (q *Queries) EndOrphanLiveStreams(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, endOrphanLiveStreams)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const forceStopLiveStream = `-- name: ForceStopLiveStream :one
UPDATE streams
SET status = 'ended', ended_at = NOW(), updated_at = NOW()
WHERE id = $1::uuid AND status = 'live' AND archived_at IS NULL
RETURNING id::text AS id
`

// Interruption par un admin (STR-192) : live -> ended SANS contrôle de
// propriétaire. L'appelant est derrière RequireRole("admin").
func (q *Queries) ForceStopLiveStream(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, forceStopLiveStream, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}

const getStreamByID = `-- name: GetStreamByID :one
SELECT id::text AS id, user_id::text AS user_id, title, description, category,
       status, is_public, stream_key, started_at, ended_at, created_at, updated_at
FROM streams
WHERE id = $1::uuid AND archived_at IS NULL
`

type GetStreamByIDRow struct {
	ID          string
	UserID      string
	Title       string
	Description pgtype.Text
	Category    pgtype.Text
	Status      string
	IsPublic    bool
	StreamKey   string
	StartedAt   *time.Time
	EndedAt     *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetStreamByID(ctx context.Context, id pgtype.UUID) (GetStreamByIDRow, error) {
	row := q.db.QueryRow(ctx, getStreamByID, id)
	var i GetStreamByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Status,
		&i.IsPublic,
		&i.StreamKey,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPublicLiveStreams = `-- name: ListPublicLiveStreams :many
SELECT id::text AS id, user_id::text AS user_id, title, description, category,
       status, is_public, started_at, ended_at, created_at, updated_at
FROM streams
WHERE is_public = true AND status = 'live' AND archived_at IS NULL
ORDER BY started_at DESC NULLS LAST, created_at DESC
LIMIT $2 OFFSET $1
`

type ListPublicLiveStreamsParams struct {
	Off int32
	Lim int32
}

type ListPublicLiveStreamsRow struct {
	ID          string
	UserID      string
	Title       string
	Description pgtype.Text
	Category    pgtype.Text
	Status      string
	IsPublic    bool
	StartedAt   *time.Time
	EndedAt     *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// Flux publics en direct, non archivés. Le stream_key n'est jamais exposé ici.
func (q *Queries) ListPublicLiveStreams(ctx context.Context, arg ListPublicLiveStreamsParams) ([]ListPublicLiveStreamsRow, error) {
	rows, err := q.db.Query(ctx, listPublicLiveStreams, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicLiveStreamsRow
	for rows.Next() {
		var i ListPublicLiveStreamsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.Status,
			&i.IsPublic,
			&i.StartedAt,
			&i.EndedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startStream = `-- name: StartStream :one
UPDATE streams AS s
SET status = 'live', started_at = NOW(), updated_at = NOW()
WHERE s.id = $1::uuid
  AND s.user_id = $2::uuid
  AND s.status = 'idle'
  AND s.archived_at IS NULL
RETURNING id::text AS id, user_id::text AS user_id, title, description, category,
          status, is_public, stream_key, started_at, ended_at, created_at, updated_at
`

type StartStreamParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

type StartStreamRow struct {
	ID          string
	UserID      string
	Title       string
	Description pgtype.Text
	Category    pgtype.Text
	Status      string
	IsPublic    bool
	StreamKey   string
	StartedAt   *time.Time
	EndedAt     *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// Passe un flux idle -> live (propriétaire, non archivé). La règle « un seul live
// par diffuseur » est garantie atomiquement par l'index unique partiel
// streams_one_live_per_user (000016) : un 2e live concurrent lève un 23505.
func (q *Queries) StartStream(ctx context.Context, arg StartStreamParams) (StartStreamRow, error) {
	row := q.db.QueryRow(ctx, startStream, arg.ID, arg.UserID)
	var i StartStreamRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Status,
		&i.IsPublic,
		&i.StreamKey,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const stopLiveStreamsByUser = `-- name: StopLiveStreamsByUser :many
UPDATE streams SET status = 'ended', ended_at = NOW(), updated_at = NOW()
WHERE user_id = $1::uuid AND status = 'live'
RETURNING id
`

func (q *Queries) StopLiveStreamsByUser(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, stopLiveStreamsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const stopStream = `-- name: StopStream :one
UPDATE streams
SET status = 'ended', ended_at = NOW(), updated_at = NOW()
WHERE id = $1::uuid AND user_id = $2::uuid
  AND status = 'live' AND archived_at IS NULL
RETURNING id::text AS id, user_id::text AS user_id, title, description, category,
          status, is_public, stream_key, started_at, ended_at, created_at, updated_at
`

type StopStreamParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

type StopStreamRow struct {
	ID          string
	UserID      string
	Title       string
	Description pgtype.Text
	Category    pgtype.Text
	Status      string
	IsPublic    bool
	StreamKey   string
	StartedAt   *time.Time
	EndedAt     *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// Passe un flux live -> ended. Réservé au propriétaire, statut live, non archivé.
func (q *Queries) StopStream(ctx context.Context, arg StopStreamParams) (StopStreamRow, error) {
	row := q.db.QueryRow(ctx, stopStream, arg.ID, arg.UserID)
	var i StopStreamRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Status,
		&i.IsPublic,
		&i.StreamKey,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStream = `-- name: UpdateStream :one
UPDATE streams
SET title = $1::text,
    description = $2::text,
    category = $3::text,
    is_public = $4::boolean,
    updated_at = NOW()
WHERE id = $5::uuid AND user_id = $6::uuid AND archived_at IS NULL
RETURNING id::text AS id, user_id::text AS user_id, title, description, category,
          status, is_public, stream_key, started_at, ended_at, created_at, updated_at
`

type UpdateStreamParams struct {
	Title       string
	Description pgtype.Text
	Category    pgtype.Text
	IsPublic    bool
	ID          pgtype.UUID
	UserID      pgtype.UUID
}

type UpdateStreamRow struct {
	ID          string
	UserID      string
	Title       string
	Description pgtype.Text
	Category    pgtype.Text
	Status      string
	IsPublic    bool
	StreamKey   string
	StartedAt   *time.Time
	EndedAt     *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) UpdateStream(ctx context.Context, arg UpdateStreamParams) (UpdateStreamRow, error) {
	row := q.db.QueryRow(ctx, updateStream,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.IsPublic,
		arg.ID,
		arg.UserID,
	)
	var i UpdateStreamRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Status,
		&i.IsPublic,
		&i.StreamKey,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
