// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: streams.sql

package streamingdb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStream = `-- name: CreateStream :one
INSERT INTO streams (user_id, title, description, category, status, is_public, stream_key)
VALUES (
    $1::uuid,
    $2::text,
    $3::text,
    $4::text,
    $5::text,
    $6::boolean,
    $7::text
)
RETURNING id::text AS id, user_id::text AS user_id, title, description, category,
          status, is_public, stream_key, created_at, updated_at
`

type CreateStreamParams struct {
	UserID      pgtype.UUID
	Title       string
	Description pgtype.Text
	Category    pgtype.Text
	Status      string
	IsPublic    bool
	StreamKey   string
}

type CreateStreamRow struct {
	ID          string
	UserID      string
	Title       string
	Description pgtype.Text
	Category    pgtype.Text
	Status      string
	IsPublic    bool
	StreamKey   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateStream(ctx context.Context, arg CreateStreamParams) (CreateStreamRow, error) {
	row := q.db.QueryRow(ctx, createStream,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.Status,
		arg.IsPublic,
		arg.StreamKey,
	)
	var i CreateStreamRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Status,
		&i.IsPublic,
		&i.StreamKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
