// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: broadcaster.sql

package broadcasterdb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBroadcasterRequest = `-- name: CreateBroadcasterRequest :one
INSERT INTO broadcaster_requests (user_id, message)
VALUES ($1::uuid, $2::text)
RETURNING id::text AS id, user_id::text AS user_id, status, message,
          review_note, reviewed_by, created_at, updated_at
`

type CreateBroadcasterRequestParams struct {
	UserID  pgtype.UUID
	Message string
}

type CreateBroadcasterRequestRow struct {
	ID         string
	UserID     string
	Status     string
	Message    string
	ReviewNote string
	ReviewedBy pgtype.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) CreateBroadcasterRequest(ctx context.Context, arg CreateBroadcasterRequestParams) (CreateBroadcasterRequestRow, error) {
	row := q.db.QueryRow(ctx, createBroadcasterRequest, arg.UserID, arg.Message)
	var i CreateBroadcasterRequestRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Message,
		&i.ReviewNote,
		&i.ReviewedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestRequestByUser = `-- name: GetLatestRequestByUser :one
SELECT id::text AS id, user_id::text AS user_id, status, message,
       review_note, reviewed_by, created_at, updated_at
FROM broadcaster_requests
WHERE user_id = $1::uuid
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestRequestByUserRow struct {
	ID         string
	UserID     string
	Status     string
	Message    string
	ReviewNote string
	ReviewedBy pgtype.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) GetLatestRequestByUser(ctx context.Context, userID pgtype.UUID) (GetLatestRequestByUserRow, error) {
	row := q.db.QueryRow(ctx, getLatestRequestByUser, userID)
	var i GetLatestRequestByUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Message,
		&i.ReviewNote,
		&i.ReviewedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRequestForReview = `-- name: GetRequestForReview :one
SELECT id::text AS id, user_id::text AS user_id, status, message,
       review_note, reviewed_by, created_at, updated_at
FROM broadcaster_requests
WHERE id = $1::uuid
FOR UPDATE
`

type GetRequestForReviewRow struct {
	ID         string
	UserID     string
	Status     string
	Message    string
	ReviewNote string
	ReviewedBy pgtype.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

// FOR UPDATE : verrouille la ligne pendant la transaction de traitement
// pour éviter qu'un second admin traite la même demande en parallèle.
func (q *Queries) GetRequestForReview(ctx context.Context, id pgtype.UUID) (GetRequestForReviewRow, error) {
	row := q.db.QueryRow(ctx, getRequestForReview, id)
	var i GetRequestForReviewRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Message,
		&i.ReviewNote,
		&i.ReviewedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserRole = `-- name: GetUserRole :one
SELECT role
FROM users
WHERE id = $1::uuid AND is_active = true
`

func (q *Queries) GetUserRole(ctx context.Context, userID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getUserRole, userID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const listBroadcasterRequests = `-- name: ListBroadcasterRequests :many
SELECT br.id::text AS id, br.user_id::text AS user_id, u.email, u.username,
       br.status, br.message, br.review_note, br.reviewed_by,
       br.created_at, br.updated_at
FROM broadcaster_requests br
JOIN users u ON u.id = br.user_id
WHERE ($1::text IS NULL OR br.status = $1::text)
ORDER BY br.created_at DESC
`

type ListBroadcasterRequestsRow struct {
	ID         string
	UserID     string
	Email      string
	Username   string
	Status     string
	Message    string
	ReviewNote string
	ReviewedBy pgtype.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) ListBroadcasterRequests(ctx context.Context, status pgtype.Text) ([]ListBroadcasterRequestsRow, error) {
	rows, err := q.db.Query(ctx, listBroadcasterRequests, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBroadcasterRequestsRow
	for rows.Next() {
		var i ListBroadcasterRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.Username,
			&i.Status,
			&i.Message,
			&i.ReviewNote,
			&i.ReviewedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteUserToBroadcaster = `-- name: PromoteUserToBroadcaster :execrows
UPDATE users
SET role = 'broadcaster', updated_at = NOW()
WHERE id = $1::uuid AND role = 'user' AND is_active = true
`

func (q *Queries) PromoteUserToBroadcaster(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, promoteUserToBroadcaster, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reviewRequest = `-- name: ReviewRequest :one
UPDATE broadcaster_requests
SET status      = $1::text,
    reviewed_by = $2::uuid,
    review_note = $3::text,
    updated_at  = NOW()
WHERE id = $4::uuid AND status = 'pending'
RETURNING id::text AS id, user_id::text AS user_id, status, message,
          review_note, reviewed_by, created_at, updated_at
`

type ReviewRequestParams struct {
	Status     string
	ReviewedBy pgtype.UUID
	ReviewNote string
	ID         pgtype.UUID
}

type ReviewRequestRow struct {
	ID         string
	UserID     string
	Status     string
	Message    string
	ReviewNote string
	ReviewedBy pgtype.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) ReviewRequest(ctx context.Context, arg ReviewRequestParams) (ReviewRequestRow, error) {
	row := q.db.QueryRow(ctx, reviewRequest,
		arg.Status,
		arg.ReviewedBy,
		arg.ReviewNote,
		arg.ID,
	)
	var i ReviewRequestRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Message,
		&i.ReviewNote,
		&i.ReviewedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
