run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports

issues:
  exclude-rules:
    - path: vendor/
      linters:
        - all
    - path: ".*\\.pb\\.go$"
      linters:
        - all
    - path: ".*\\.gen\\.go$"
      linters:
        - all
