// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package admindb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminCountActiveAdmins = `-- name: AdminCountActiveAdmins :one
SELECT COUNT(*) FROM users WHERE role = 'admin' AND is_active = true
`

func (q *Queries) AdminCountActiveAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountActiveAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminCountUsers = `-- name: AdminCountUsers :one
SELECT COUNT(*)
FROM users
WHERE ($1::text = '' OR email ILIKE '%' || $1 || '%' ESCAPE '\' OR username ILIKE '%' || $1 || '%' ESCAPE '\')
  AND ($2::text = '' OR role = $2)
  AND ($3::text = ''
       OR ($3 = 'active' AND is_active)
       OR ($3 = 'inactive' AND NOT is_active))
`

type AdminCountUsersParams struct {
	Search       string
	RoleFilter   string
	StatusFilter string
}

// Total de pagination indépendant de LIMIT/OFFSET (cf. revue PR #264 fix #2) :
// COUNT(*) OVER() n'est porté que par les lignes renvoyées par AdminListUsers,
// donc une page vide (offset au-delà du nombre de lignes filtrées) renvoyait
// total=0 au lieu du vrai total de correspondances. Mêmes filtres que
// AdminListUsers, sans LIMIT/OFFSET.
func (q *Queries) AdminCountUsers(ctx context.Context, arg AdminCountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountUsers, arg.Search, arg.RoleFilter, arg.StatusFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminDeleteUser = `-- name: AdminDeleteUser :execrows
DELETE FROM users WHERE id = $1::uuid
`

func (q *Queries) AdminDeleteUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, adminDeleteUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminGetUser = `-- name: AdminGetUser :one
SELECT id, email, username, role, is_active, created_at FROM users WHERE id = $1::uuid
`

type AdminGetUserRow struct {
	ID        pgtype.UUID
	Email     string
	Username  string
	Role      string
	IsActive  bool
	CreatedAt time.Time
}

func (q *Queries) AdminGetUser(ctx context.Context, userID pgtype.UUID) (AdminGetUserRow, error) {
	row := q.db.QueryRow(ctx, adminGetUser, userID)
	var i AdminGetUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const adminListUsers = `-- name: AdminListUsers :many
SELECT id, email, username, role, is_active, created_at
FROM users
WHERE ($1::text = '' OR email ILIKE '%' || $1 || '%' ESCAPE '\' OR username ILIKE '%' || $1 || '%' ESCAPE '\')
  AND ($2::text = '' OR role = $2)
  AND ($3::text = ''
       OR ($3 = 'active' AND is_active)
       OR ($3 = 'inactive' AND NOT is_active))
ORDER BY created_at DESC, id DESC
LIMIT $5 OFFSET $4
`

type AdminListUsersParams struct {
	Search       string
	RoleFilter   string
	StatusFilter string
	Off          int32
	Lim          int32
}

type AdminListUsersRow struct {
	ID        pgtype.UUID
	Email     string
	Username  string
	Role      string
	IsActive  bool
	CreatedAt time.Time
}

// Le terme de recherche est échappé côté repository (escapeLikePattern) avant
// d'arriver ici : '\' est le caractère d'échappement explicite (ESCAPE '\'),
// pour que '_' et '%' tapés par l'utilisateur soient littéraux, pas des
// jokers ILIKE (cf. revue PR #264 fix #4).
func (q *Queries) AdminListUsers(ctx context.Context, arg AdminListUsersParams) ([]AdminListUsersRow, error) {
	rows, err := q.db.Query(ctx, adminListUsers,
		arg.Search,
		arg.RoleFilter,
		arg.StatusFilter,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListUsersRow
	for rows.Next() {
		var i AdminListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminSetUserActive = `-- name: AdminSetUserActive :one
UPDATE users SET is_active = $1, updated_at = NOW()
WHERE id = $2::uuid
RETURNING id, email, username, role, is_active, created_at
`

type AdminSetUserActiveParams struct {
	Active bool
	UserID pgtype.UUID
}

type AdminSetUserActiveRow struct {
	ID        pgtype.UUID
	Email     string
	Username  string
	Role      string
	IsActive  bool
	CreatedAt time.Time
}

func (q *Queries) AdminSetUserActive(ctx context.Context, arg AdminSetUserActiveParams) (AdminSetUserActiveRow, error) {
	row := q.db.QueryRow(ctx, adminSetUserActive, arg.Active, arg.UserID)
	var i AdminSetUserActiveRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
