// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package admindb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminCountActiveAdmins = `-- name: AdminCountActiveAdmins :one
SELECT COUNT(*) FROM users WHERE role = 'admin' AND is_active = true
`

func (q *Queries) AdminCountActiveAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountActiveAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminCountLiveStreams = `-- name: AdminCountLiveStreams :one
SELECT COUNT(*) FROM streams s
WHERE s.status = 'live' AND s.archived_at IS NULL
`

// Total séparé (COUNT(*) OVER() renvoie 0 sur page vide — cf. review STR-191).
func (q *Queries) AdminCountLiveStreams(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountLiveStreams)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminCountUsers = `-- name: AdminCountUsers :one
SELECT COUNT(*)
FROM users
WHERE ($1::text = '' OR email ILIKE '%' || $1 || '%' ESCAPE '\' OR username ILIKE '%' || $1 || '%' ESCAPE '\')
  AND ($2::text = '' OR role = $2)
  AND ($3::text = ''
       OR ($3 = 'active' AND is_active)
       OR ($3 = 'inactive' AND NOT is_active))
`

type AdminCountUsersParams struct {
	Search       string
	RoleFilter   string
	StatusFilter string
}

// Total de pagination indépendant de LIMIT/OFFSET (cf. revue PR #264 fix #2) :
// COUNT(*) OVER() n'est porté que par les lignes renvoyées par AdminListUsers,
// donc une page vide (offset au-delà du nombre de lignes filtrées) renvoyait
// total=0 au lieu du vrai total de correspondances. Mêmes filtres que
// AdminListUsers, sans LIMIT/OFFSET.
func (q *Queries) AdminCountUsers(ctx context.Context, arg AdminCountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountUsers, arg.Search, arg.RoleFilter, arg.StatusFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminDeleteUser = `-- name: AdminDeleteUser :execrows
DELETE FROM users WHERE id = $1::uuid
`

func (q *Queries) AdminDeleteUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, adminDeleteUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminGetUser = `-- name: AdminGetUser :one
SELECT id, email, username, role, is_active, created_at FROM users WHERE id = $1::uuid
`

type AdminGetUserRow struct {
	ID        pgtype.UUID
	Email     string
	Username  string
	Role      string
	IsActive  bool
	CreatedAt time.Time
}

func (q *Queries) AdminGetUser(ctx context.Context, userID pgtype.UUID) (AdminGetUserRow, error) {
	row := q.db.QueryRow(ctx, adminGetUser, userID)
	var i AdminGetUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const adminListLiveStreams = `-- name: AdminListLiveStreams :many
SELECT s.id, s.title, s.is_public, s.started_at, s.user_id, u.username
FROM streams s
JOIN users u ON u.id = s.user_id
WHERE s.status = 'live' AND s.archived_at IS NULL
ORDER BY s.started_at DESC, s.id DESC
LIMIT $2 OFFSET $1
`

type AdminListLiveStreamsParams struct {
	Off int32
	Lim int32
}

type AdminListLiveStreamsRow struct {
	ID        pgtype.UUID
	Title     string
	IsPublic  bool
	StartedAt pgtype.Timestamptz
	UserID    pgtype.UUID
	Username  string
}

// Liste de modération (STR-192) : TOUS les flux en direct, publics ET privés,
// avec l'identité du diffuseur. Tri stable (started_at puis id).
func (q *Queries) AdminListLiveStreams(ctx context.Context, arg AdminListLiveStreamsParams) ([]AdminListLiveStreamsRow, error) {
	rows, err := q.db.Query(ctx, adminListLiveStreams, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListLiveStreamsRow
	for rows.Next() {
		var i AdminListLiveStreamsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.IsPublic,
			&i.StartedAt,
			&i.UserID,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListUsers = `-- name: AdminListUsers :many
SELECT id, email, username, role, is_active, created_at
FROM users
WHERE ($1::text = '' OR email ILIKE '%' || $1 || '%' ESCAPE '\' OR username ILIKE '%' || $1 || '%' ESCAPE '\')
  AND ($2::text = '' OR role = $2)
  AND ($3::text = ''
       OR ($3 = 'active' AND is_active)
       OR ($3 = 'inactive' AND NOT is_active))
ORDER BY created_at DESC, id DESC
LIMIT $5 OFFSET $4
`

type AdminListUsersParams struct {
	Search       string
	RoleFilter   string
	StatusFilter string
	Off          int32
	Lim          int32
}

type AdminListUsersRow struct {
	ID        pgtype.UUID
	Email     string
	Username  string
	Role      string
	IsActive  bool
	CreatedAt time.Time
}

// Le terme de recherche est échappé côté repository (escapeLikePattern) avant
// d'arriver ici : '\' est le caractère d'échappement explicite (ESCAPE '\'),
// pour que '_' et '%' tapés par l'utilisateur soient littéraux, pas des
// jokers ILIKE (cf. revue PR #264 fix #4).
func (q *Queries) AdminListUsers(ctx context.Context, arg AdminListUsersParams) ([]AdminListUsersRow, error) {
	rows, err := q.db.Query(ctx, adminListUsers,
		arg.Search,
		arg.RoleFilter,
		arg.StatusFilter,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListUsersRow
	for rows.Next() {
		var i AdminListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminSetUserActive = `-- name: AdminSetUserActive :one
UPDATE users SET is_active = $1, updated_at = NOW()
WHERE id = $2::uuid
RETURNING id, email, username, role, is_active, created_at
`

type AdminSetUserActiveParams struct {
	Active bool
	UserID pgtype.UUID
}

type AdminSetUserActiveRow struct {
	ID        pgtype.UUID
	Email     string
	Username  string
	Role      string
	IsActive  bool
	CreatedAt time.Time
}

func (q *Queries) AdminSetUserActive(ctx context.Context, arg AdminSetUserActiveParams) (AdminSetUserActiveRow, error) {
	row := q.db.QueryRow(ctx, adminSetUserActive, arg.Active, arg.UserID)
	var i AdminSetUserActiveRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const adminUserCounts = `-- name: AdminUserCounts :one
SELECT
  COUNT(*)                                     AS total,
  COUNT(*) FILTER (WHERE is_active)            AS active,
  COUNT(*) FILTER (WHERE role = 'broadcaster') AS broadcasters,
  COUNT(*) FILTER (WHERE role = 'admin')       AS admins
FROM users
`

type AdminUserCountsRow struct {
	Total        int64
	Active       int64
	Broadcasters int64
	Admins       int64
}

// Résumé de population pour GET /api/admin/metrics (STR-244) : une seule
// requête plutôt que quatre COUNT successifs, les agrégats filtrés partageant
// le même balayage.
func (q *Queries) AdminUserCounts(ctx context.Context) (AdminUserCountsRow, error) {
	row := q.db.QueryRow(ctx, adminUserCounts)
	var i AdminUserCountsRow
	err := row.Scan(
		&i.Total,
		&i.Active,
		&i.Broadcasters,
		&i.Admins,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (actor_id, action, target_type, target_id)
VALUES ($1::uuid, $2, $3, $4::uuid)
`

type InsertAuditLogParams struct {
	ActorID    pgtype.UUID
	Action     string
	TargetType string
	TargetID   pgtype.UUID
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ActorID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
	)
	return err
}
