// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package trackdb

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID         pgtype.UUID
	ActorID    pgtype.UUID
	Action     string
	TargetType string
	TargetID   pgtype.UUID
	CreatedAt  time.Time
}

type BroadcasterRequest struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	Status     string
	Message    string
	ReviewedBy pgtype.UUID
	ReviewNote string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Favorite struct {
	UserID    pgtype.UUID
	StreamID  pgtype.UUID
	CreatedAt time.Time
}

type PasswordResetToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash string
	ExpiresAt time.Time
	UsedAt    pgtype.Timestamptz
	CreatedAt time.Time
}

type Playlist struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Name        string
	Description pgtype.Text
	IsPublic    bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type PlaylistTrack struct {
	PlaylistID pgtype.UUID
	TrackID    pgtype.UUID
	Position   int32
	AddedAt    time.Time
}

type Profile struct {
	ID                   pgtype.UUID
	UserID               pgtype.UUID
	Pseudo               pgtype.Text
	Bio                  string
	AvatarUrl            pgtype.Text
	CreatedAt            time.Time
	UpdatedAt            time.Time
	Theme                string
	NotificationsEnabled bool
	AudioQuality         string
}

type QueueItem struct {
	ID       pgtype.UUID
	UserID   pgtype.UUID
	TrackID  pgtype.UUID
	Position int32
	AddedAt  time.Time
}

type RefreshToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash string
	ExpiresAt time.Time
	CreatedAt time.Time
}

type Stream struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Title       string
	Description pgtype.Text
	Category    pgtype.Text
	Status      string
	IsPublic    bool
	StartedAt   pgtype.Timestamptz
	EndedAt     pgtype.Timestamptz
	CreatedAt   time.Time
	UpdatedAt   time.Time
	StreamKey   string
	ArchivedAt  pgtype.Timestamptz
}

type Track struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Title     string
	Artist    pgtype.Text
	DurationS pgtype.Int4
	FilePath  string
	MimeType  string
	FileSize  int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID           pgtype.UUID
	Email        string
	Username     string
	PasswordHash string
	Role         string
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
