// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tracks.sql

package trackdb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTrack = `-- name: CreateTrack :one
INSERT INTO tracks (user_id, title, artist, duration_s, file_path, mime_type, file_size, is_public)
VALUES (
    $1::uuid,
    $2::text,
    $3::text,
    $4::int,
    $5::text,
    $6::text,
    $7::bigint,
    $8::boolean
)
RETURNING id::text AS id, title, artist, duration_s, is_public
`

type CreateTrackParams struct {
	UserID    pgtype.UUID
	Title     string
	Artist    pgtype.Text
	DurationS pgtype.Int4
	FilePath  string
	MimeType  string
	FileSize  int64
	IsPublic  bool
}

type CreateTrackRow struct {
	ID        string
	Title     string
	Artist    pgtype.Text
	DurationS pgtype.Int4
	IsPublic  bool
}

// Enregistre une piste uploadée dans la bibliothèque du demandeur. Le fichier est
// déjà écrit sur disque (file_path). mime_type est validé côté serveur et doit
// appartenir au CHECK de la table (audio/mpeg|aac|ogg). La contrainte
// uq_tracks_user_title (000006) rend un titre en doublon -> 23505 -> 409 au repo.
func (q *Queries) CreateTrack(ctx context.Context, arg CreateTrackParams) (CreateTrackRow, error) {
	row := q.db.QueryRow(ctx, createTrack,
		arg.UserID,
		arg.Title,
		arg.Artist,
		arg.DurationS,
		arg.FilePath,
		arg.MimeType,
		arg.FileSize,
		arg.IsPublic,
	)
	var i CreateTrackRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Artist,
		&i.DurationS,
		&i.IsPublic,
	)
	return i, err
}

const deleteTrack = `-- name: DeleteTrack :one
DELETE FROM tracks
WHERE id = $1::uuid
  AND user_id = $2::uuid
RETURNING file_path
`

type DeleteTrackParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

// Suppression d'une piste par son propriétaire. Retourne le chemin du fichier
// pour le supprimer du stockage après le DELETE. La FK ON DELETE CASCADE sur
// playlist_tracks retire automatiquement la piste de toutes les playlists.
// 0 ligne = piste inexistante ou d'un tiers -> 404 au repo.
func (q *Queries) DeleteTrack(ctx context.Context, arg DeleteTrackParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteTrack, arg.ID, arg.UserID)
	var file_path string
	err := row.Scan(&file_path)
	return file_path, err
}

const getTrackFileByUser = `-- name: GetTrackFileByUser :one
SELECT file_path, mime_type
FROM tracks
WHERE id = $1::uuid
  AND user_id = $2::uuid
`

type GetTrackFileByUserParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

type GetTrackFileByUserRow struct {
	FilePath string
	MimeType string
}

// Localise le binaire d'une piste **du demandeur**, pour le servir en lecture
// (US-05-04). Le filtre porte sur (id, user_id) : la piste d'un tiers ne se
// distingue pas d'une piste inexistante (0 ligne -> 404), donc l'API ne révèle
// pas l'existence de la bibliothèque d'autrui.
func (q *Queries) GetTrackFileByUser(ctx context.Context, arg GetTrackFileByUserParams) (GetTrackFileByUserRow, error) {
	row := q.db.QueryRow(ctx, getTrackFileByUser, arg.ID, arg.UserID)
	var i GetTrackFileByUserRow
	err := row.Scan(&i.FilePath, &i.MimeType)
	return i, err
}

const getTrackFileForStream = `-- name: GetTrackFileForStream :one
SELECT file_path, mime_type
FROM tracks
WHERE id = $1::uuid
  AND (user_id = $2::uuid OR is_public = true)
`

type GetTrackFileForStreamParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

type GetTrackFileForStreamRow struct {
	FilePath string
	MimeType string
}

// Localise le binaire d'une piste accessible au demandeur : soit sa propre piste,
// soit une piste publique d'un tiers.
func (q *Queries) GetTrackFileForStream(ctx context.Context, arg GetTrackFileForStreamParams) (GetTrackFileForStreamRow, error) {
	row := q.db.QueryRow(ctx, getTrackFileForStream, arg.ID, arg.UserID)
	var i GetTrackFileForStreamRow
	err := row.Scan(&i.FilePath, &i.MimeType)
	return i, err
}

const listFilePathsByUser = `-- name: ListFilePathsByUser :many
SELECT file_path
FROM tracks
WHERE user_id = $1::uuid
`

// Chemins disque des fichiers du demandeur, pour les supprimer du stockage lors
// de la suppression de son compte (la cascade DB efface les lignes, pas les
// fichiers).
func (q *Queries) ListFilePathsByUser(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listFilePathsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var file_path string
		if err := rows.Scan(&file_path); err != nil {
			return nil, err
		}
		items = append(items, file_path)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicTracks = `-- name: ListPublicTracks :many
SELECT t.id::text AS id, t.title, t.artist, t.duration_s,
       t.created_at, u.username AS owner_name
FROM tracks t
JOIN users u ON u.id = t.user_id
WHERE t.is_public = true
  AND (t.created_at, t.id) < ($1::timestamptz, $2::uuid)
ORDER BY t.created_at DESC, t.id DESC
LIMIT $3::int
`

type ListPublicTracksParams struct {
	CursorCreatedAt pgtype.Timestamptz
	CursorID        pgtype.UUID
	PageSize        int32
}

type ListPublicTracksRow struct {
	ID        string
	Title     string
	Artist    pgtype.Text
	DurationS pgtype.Int4
	CreatedAt time.Time
	OwnerName string
}

// Pistes publiques de tous les utilisateurs, pour l'écran de découverte.
// Paginé par curseur (created_at DESC, id DESC).
func (q *Queries) ListPublicTracks(ctx context.Context, arg ListPublicTracksParams) ([]ListPublicTracksRow, error) {
	rows, err := q.db.Query(ctx, listPublicTracks, arg.CursorCreatedAt, arg.CursorID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicTracksRow
	for rows.Next() {
		var i ListPublicTracksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Artist,
			&i.DurationS,
			&i.CreatedAt,
			&i.OwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicTracksFirst = `-- name: ListPublicTracksFirst :many
SELECT t.id::text AS id, t.title, t.artist, t.duration_s,
       t.created_at, u.username AS owner_name
FROM tracks t
JOIN users u ON u.id = t.user_id
WHERE t.is_public = true
ORDER BY t.created_at DESC, t.id DESC
LIMIT $1::int
`

type ListPublicTracksFirstRow struct {
	ID        string
	Title     string
	Artist    pgtype.Text
	DurationS pgtype.Int4
	CreatedAt time.Time
	OwnerName string
}

// Première page de pistes publiques (pas de curseur).
func (q *Queries) ListPublicTracksFirst(ctx context.Context, pageSize int32) ([]ListPublicTracksFirstRow, error) {
	rows, err := q.db.Query(ctx, listPublicTracksFirst, pageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicTracksFirstRow
	for rows.Next() {
		var i ListPublicTracksFirstRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Artist,
			&i.DurationS,
			&i.CreatedAt,
			&i.OwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracksByUser = `-- name: ListTracksByUser :many
SELECT id::text AS id, title, artist, duration_s, is_public
FROM tracks
WHERE user_id = $1::uuid
ORDER BY created_at DESC
`

type ListTracksByUserRow struct {
	ID        string
	Title     string
	Artist    pgtype.Text
	DurationS pgtype.Int4
	IsPublic  bool
}

// Bibliothèque de pistes du demandeur (source du sélecteur « ajouter une piste »
// côté mobile). Les plus récentes d'abord.
func (q *Queries) ListTracksByUser(ctx context.Context, userID pgtype.UUID) ([]ListTracksByUserRow, error) {
	rows, err := q.db.Query(ctx, listTracksByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTracksByUserRow
	for rows.Next() {
		var i ListTracksByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Artist,
			&i.DurationS,
			&i.IsPublic,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumTrackSizeByUser = `-- name: SumTrackSizeByUser :one
SELECT COALESCE(SUM(file_size), 0)::bigint AS total
FROM tracks
WHERE user_id = $1::uuid
`

// Taille cumulée des fichiers du demandeur, pour appliquer le quota de stockage
// par compte avant un nouvel upload (borne le remplissage du volume).
func (q *Queries) SumTrackSizeByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumTrackSizeByUser, userID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const updateTrackVisibility = `-- name: UpdateTrackVisibility :execrows
UPDATE tracks
SET is_public = $1::boolean, updated_at = NOW()
WHERE id = $2::uuid
  AND user_id = $3::uuid
`

type UpdateTrackVisibilityParams struct {
	IsPublic bool
	ID       pgtype.UUID
	UserID   pgtype.UUID
}

// Modifie la visibilité d'une piste. Filtre sur (id, user_id) : seul le
// propriétaire peut changer la visibilité de sa piste.
func (q *Queries) UpdateTrackVisibility(ctx context.Context, arg UpdateTrackVisibilityParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTrackVisibility, arg.IsPublic, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
