// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tracks.sql

package trackdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTrack = `-- name: CreateTrack :one
INSERT INTO tracks (user_id, title, artist, duration_s, file_path, mime_type, file_size)
VALUES (
    $1::uuid,
    $2::text,
    $3::text,
    $4::int,
    $5::text,
    $6::text,
    $7::bigint
)
RETURNING id::text AS id, title, artist, duration_s
`

type CreateTrackParams struct {
	UserID    pgtype.UUID
	Title     string
	Artist    pgtype.Text
	DurationS pgtype.Int4
	FilePath  string
	MimeType  string
	FileSize  int64
}

type CreateTrackRow struct {
	ID        string
	Title     string
	Artist    pgtype.Text
	DurationS pgtype.Int4
}

// Enregistre une piste uploadée dans la bibliothèque du demandeur. Le fichier est
// déjà écrit sur disque (file_path). mime_type est validé côté serveur et doit
// appartenir au CHECK de la table (audio/mpeg|aac|ogg). La contrainte
// uq_tracks_user_title (000006) rend un titre en doublon -> 23505 -> 409 au repo.
func (q *Queries) CreateTrack(ctx context.Context, arg CreateTrackParams) (CreateTrackRow, error) {
	row := q.db.QueryRow(ctx, createTrack,
		arg.UserID,
		arg.Title,
		arg.Artist,
		arg.DurationS,
		arg.FilePath,
		arg.MimeType,
		arg.FileSize,
	)
	var i CreateTrackRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Artist,
		&i.DurationS,
	)
	return i, err
}

const listFilePathsByUser = `-- name: ListFilePathsByUser :many
SELECT file_path
FROM tracks
WHERE user_id = $1::uuid
`

// Chemins disque des fichiers du demandeur, pour les supprimer du stockage lors
// de la suppression de son compte (la cascade DB efface les lignes, pas les
// fichiers).
func (q *Queries) ListFilePathsByUser(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listFilePathsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var file_path string
		if err := rows.Scan(&file_path); err != nil {
			return nil, err
		}
		items = append(items, file_path)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracksByUser = `-- name: ListTracksByUser :many
SELECT id::text AS id, title, artist, duration_s
FROM tracks
WHERE user_id = $1::uuid
ORDER BY created_at DESC
`

type ListTracksByUserRow struct {
	ID        string
	Title     string
	Artist    pgtype.Text
	DurationS pgtype.Int4
}

// Bibliothèque de pistes du demandeur (source du sélecteur « ajouter une piste »
// côté mobile). Les plus récentes d'abord.
func (q *Queries) ListTracksByUser(ctx context.Context, userID pgtype.UUID) ([]ListTracksByUserRow, error) {
	rows, err := q.db.Query(ctx, listTracksByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTracksByUserRow
	for rows.Next() {
		var i ListTracksByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Artist,
			&i.DurationS,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumTrackSizeByUser = `-- name: SumTrackSizeByUser :one
SELECT COALESCE(SUM(file_size), 0)::bigint AS total
FROM tracks
WHERE user_id = $1::uuid
`

// Taille cumulée des fichiers du demandeur, pour appliquer le quota de stockage
// par compte avant un nouvel upload (borne le remplissage du volume).
func (q *Queries) SumTrackSizeByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumTrackSizeByUser, userID)
	var total int64
	err := row.Scan(&total)
	return total, err
}
