// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package authdb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, username, password_hash)
VALUES ($1, $2, $3)
RETURNING id::text, email, username, role, created_at
`

type CreateUserParams struct {
	Email        string
	Username     string
	PasswordHash string
}

type CreateUserRow struct {
	ID        string
	Email     string
	Username  string
	Role      string
	CreatedAt time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Username, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAllRefreshTokensByUser = `-- name: DeleteAllRefreshTokensByUser :exec
DELETE FROM refresh_tokens WHERE user_id = $1::uuid
`

func (q *Queries) DeleteAllRefreshTokensByUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllRefreshTokensByUser, userID)
	return err
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :execresult
DELETE FROM refresh_tokens WHERE token_hash = $1
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, tokenHash string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteRefreshToken, tokenHash)
}

const deleteUserByID = `-- name: DeleteUserByID :exec
DELETE FROM users WHERE id = $1::uuid
`

func (q *Queries) DeleteUserByID(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserByID, userID)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id::text, email, username, role, created_at, password_hash
FROM users
WHERE email = $1 AND is_active = true
`

type GetUserByEmailRow struct {
	ID           string
	Email        string
	Username     string
	Role         string
	CreatedAt    time.Time
	PasswordHash string
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Role,
		&i.CreatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id::text, email, username, role, created_at, password_hash
FROM users
WHERE id = $1::uuid AND is_active = true
`

type GetUserByIDRow struct {
	ID           string
	Email        string
	Username     string
	Role         string
	CreatedAt    time.Time
	PasswordHash string
}

func (q *Queries) GetUserByID(ctx context.Context, userID pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Role,
		&i.CreatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByRefreshToken = `-- name: GetUserByRefreshToken :one
SELECT u.id::text AS id, u.email, u.username, u.role, u.created_at
FROM refresh_tokens rt
JOIN users u ON u.id = rt.user_id
WHERE rt.token_hash = $1
  AND rt.expires_at > NOW()
  AND u.is_active = true
`

type GetUserByRefreshTokenRow struct {
	ID        string
	Email     string
	Username  string
	Role      string
	CreatedAt time.Time
}

func (q *Queries) GetUserByRefreshToken(ctx context.Context, tokenHash string) (GetUserByRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, getUserByRefreshToken, tokenHash)
	var i GetUserByRefreshTokenRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO refresh_tokens (user_id, token_hash, expires_at)
VALUES ($1::uuid, $2, $3)
`

type InsertRefreshTokenParams struct {
	UserID    pgtype.UUID
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, insertRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}
