// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_reset.sql

package authdb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertPasswordResetToken = `-- name: InsertPasswordResetToken :exec
INSERT INTO password_reset_tokens (user_id, token_hash, expires_at)
VALUES ($1::uuid, $2, $3)
`

type InsertPasswordResetTokenParams struct {
	UserID    pgtype.UUID
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) InsertPasswordResetToken(ctx context.Context, arg InsertPasswordResetTokenParams) error {
	_, err := q.db.Exec(ctx, insertPasswordResetToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const deletePendingPasswordResetsByUser = `-- name: DeletePendingPasswordResetsByUser :exec
DELETE FROM password_reset_tokens
WHERE user_id = $1::uuid
  AND used_at IS NULL
`

func (q *Queries) DeletePendingPasswordResetsByUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePendingPasswordResetsByUser, userID)
	return err
}
