// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: favorites.sql

package playlistdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPlaylistFavorite = `-- name: AddPlaylistFavorite :exec
INSERT INTO playlist_favorites (user_id, playlist_id)
VALUES ($1::uuid, $2::uuid)
ON CONFLICT DO NOTHING
`

type AddPlaylistFavoriteParams struct {
	UserID     pgtype.UUID
	PlaylistID pgtype.UUID
}

// Ajout idempotent : un favori déjà présent ne lève pas d'erreur.
func (q *Queries) AddPlaylistFavorite(ctx context.Context, arg AddPlaylistFavoriteParams) error {
	_, err := q.db.Exec(ctx, addPlaylistFavorite, arg.UserID, arg.PlaylistID)
	return err
}

const removePlaylistFavorite = `-- name: RemovePlaylistFavorite :exec
DELETE FROM playlist_favorites
WHERE user_id = $1::uuid AND playlist_id = $2::uuid
`

type RemovePlaylistFavoriteParams struct {
	UserID     pgtype.UUID
	PlaylistID pgtype.UUID
}

// Suppression idempotente : aucun effet si le favori n'existe pas.
func (q *Queries) RemovePlaylistFavorite(ctx context.Context, arg RemovePlaylistFavoriteParams) error {
	_, err := q.db.Exec(ctx, removePlaylistFavorite, arg.UserID, arg.PlaylistID)
	return err
}
