// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: favorites.sql

package playlistdb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPlaylistFavorite = `-- name: AddPlaylistFavorite :exec
INSERT INTO playlist_favorites (user_id, playlist_id)
VALUES ($1::uuid, $2::uuid)
ON CONFLICT DO NOTHING
`

type AddPlaylistFavoriteParams struct {
	UserID     pgtype.UUID
	PlaylistID pgtype.UUID
}

// Ajout idempotent : un favori déjà présent ne lève pas d'erreur.
func (q *Queries) AddPlaylistFavorite(ctx context.Context, arg AddPlaylistFavoriteParams) error {
	_, err := q.db.Exec(ctx, addPlaylistFavorite, arg.UserID, arg.PlaylistID)
	return err
}

const listFavoritePlaylistsByUser = `-- name: ListFavoritePlaylistsByUser :many
SELECT p.id::text AS id, p.user_id::text AS user_id, p.name, p.description, p.is_public,
       COUNT(pt.track_id) AS track_count,
       true AS is_favorite,
       p.created_at, p.updated_at
FROM playlist_favorites pf
JOIN playlists p ON p.id = pf.playlist_id
LEFT JOIN playlist_tracks pt ON pt.playlist_id = p.id
WHERE pf.user_id = $1::uuid
GROUP BY p.id, pf.created_at
ORDER BY pf.created_at DESC
`

type ListFavoritePlaylistsByUserRow struct {
	ID          string
	UserID      string
	Name        string
	Description pgtype.Text
	IsPublic    bool
	TrackCount  int64
	IsFavorite  bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// Playlists épinglées par le demandeur, avec leur nombre de pistes, triées par
// date d'ajout du favori (desc). is_favorite est toujours vrai ici.
func (q *Queries) ListFavoritePlaylistsByUser(ctx context.Context, userID pgtype.UUID) ([]ListFavoritePlaylistsByUserRow, error) {
	rows, err := q.db.Query(ctx, listFavoritePlaylistsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFavoritePlaylistsByUserRow
	for rows.Next() {
		var i ListFavoritePlaylistsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.IsPublic,
			&i.TrackCount,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePlaylistFavorite = `-- name: RemovePlaylistFavorite :exec
DELETE FROM playlist_favorites
WHERE user_id = $1::uuid AND playlist_id = $2::uuid
`

type RemovePlaylistFavoriteParams struct {
	UserID     pgtype.UUID
	PlaylistID pgtype.UUID
}

// Suppression idempotente : aucun effet si le favori n'existe pas.
func (q *Queries) RemovePlaylistFavorite(ctx context.Context, arg RemovePlaylistFavoriteParams) error {
	_, err := q.db.Exec(ctx, removePlaylistFavorite, arg.UserID, arg.PlaylistID)
	return err
}
