// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: playlists.sql

package playlistdb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTrackToPlaylist = `-- name: AddTrackToPlaylist :one
INSERT INTO playlist_tracks (playlist_id, track_id, position)
SELECT $1::uuid,
       t.id,
       COALESCE(
           (SELECT MAX(pt.position) + 1
            FROM playlist_tracks pt
            WHERE pt.playlist_id = $1::uuid),
           0
       )
FROM tracks t
WHERE t.id = $2::uuid
  AND t.user_id = $3::uuid
RETURNING track_id::text AS track_id, position
`

type AddTrackToPlaylistParams struct {
	PlaylistID pgtype.UUID
	TrackID    pgtype.UUID
	UserID     pgtype.UUID
}

type AddTrackToPlaylistRow struct {
	TrackID  string
	Position int32
}

// Ajout en fin de playlist. Le SELECT source restreint aux pistes du demandeur :
// une piste inconnue ou appartenant à un tiers ne produit aucune ligne -> le
// repo renvoie NotFound. Une piste déjà présente viole la PK -> 23505 -> 409.
func (q *Queries) AddTrackToPlaylist(ctx context.Context, arg AddTrackToPlaylistParams) (AddTrackToPlaylistRow, error) {
	row := q.db.QueryRow(ctx, addTrackToPlaylist, arg.PlaylistID, arg.TrackID, arg.UserID)
	var i AddTrackToPlaylistRow
	err := row.Scan(&i.TrackID, &i.Position)
	return i, err
}

const countPlaylistTracks = `-- name: CountPlaylistTracks :one
SELECT COUNT(*) AS total
FROM playlist_tracks
WHERE playlist_id = $1::uuid
`

func (q *Queries) CountPlaylistTracks(ctx context.Context, playlistID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPlaylistTracks, playlistID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createPlaylist = `-- name: CreatePlaylist :one
INSERT INTO playlists (user_id, name, description)
VALUES (
    $1::uuid,
    $2::text,
    $3::text
)
RETURNING id::text AS id, user_id::text AS user_id, name, description, is_public,
          0::bigint AS track_count, created_at, updated_at
`

type CreatePlaylistParams struct {
	UserID      pgtype.UUID
	Name        string
	Description pgtype.Text
}

type CreatePlaylistRow struct {
	ID          string
	UserID      string
	Name        string
	Description pgtype.Text
	IsPublic    bool
	TrackCount  int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// Création d'une playlist vide. La contrainte uq_playlists_user_name (000006)
// garantit l'unicité (user_id, name) : un doublon lève un 23505 -> 409 au repo.
func (q *Queries) CreatePlaylist(ctx context.Context, arg CreatePlaylistParams) (CreatePlaylistRow, error) {
	row := q.db.QueryRow(ctx, createPlaylist, arg.UserID, arg.Name, arg.Description)
	var i CreatePlaylistRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.TrackCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePlaylist = `-- name: DeletePlaylist :one
DELETE FROM playlists
WHERE id = $1::uuid AND user_id = $2::uuid
RETURNING id::text AS id
`

type DeletePlaylistParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

// Suppression définitive, restreinte au propriétaire. playlist_tracks est purgé
// en cascade (FK ON DELETE CASCADE). 0 ligne -> NotFound.
func (q *Queries) DeletePlaylist(ctx context.Context, arg DeletePlaylistParams) (string, error) {
	row := q.db.QueryRow(ctx, deletePlaylist, arg.ID, arg.UserID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getPlaylistByID = `-- name: GetPlaylistByID :one
SELECT p.id::text AS id, p.user_id::text AS user_id, p.name, p.description, p.is_public,
       COUNT(pt.track_id) AS track_count, p.created_at, p.updated_at
FROM playlists p
LEFT JOIN playlist_tracks pt ON pt.playlist_id = p.id
WHERE p.id = $1::uuid
GROUP BY p.id
`

type GetPlaylistByIDRow struct {
	ID          string
	UserID      string
	Name        string
	Description pgtype.Text
	IsPublic    bool
	TrackCount  int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// Une playlist par id (avec track_count). Le contrôle de propriété est fait par
// le service à partir du user_id renvoyé.
func (q *Queries) GetPlaylistByID(ctx context.Context, id pgtype.UUID) (GetPlaylistByIDRow, error) {
	row := q.db.QueryRow(ctx, getPlaylistByID, id)
	var i GetPlaylistByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.TrackCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlaylistTracks = `-- name: ListPlaylistTracks :many
SELECT t.id::text AS id, t.title, t.artist, t.duration_s, pt.position
FROM playlist_tracks pt
JOIN tracks t ON t.id = pt.track_id
WHERE pt.playlist_id = $1::uuid
ORDER BY pt.position
`

type ListPlaylistTracksRow struct {
	ID        string
	Title     string
	Artist    pgtype.Text
	DurationS pgtype.Int4
	Position  int32
}

// Pistes d'une playlist, ordonnées par position. artist et duration_s sont
// nullables (cf. table tracks). Le contrôle de propriété de la playlist est fait
// par le service en amont.
func (q *Queries) ListPlaylistTracks(ctx context.Context, playlistID pgtype.UUID) ([]ListPlaylistTracksRow, error) {
	rows, err := q.db.Query(ctx, listPlaylistTracks, playlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlaylistTracksRow
	for rows.Next() {
		var i ListPlaylistTracksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Artist,
			&i.DurationS,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaylistsByUser = `-- name: ListPlaylistsByUser :many
SELECT p.id::text AS id, p.user_id::text AS user_id, p.name, p.description, p.is_public,
       COUNT(pt.track_id) AS track_count, p.created_at, p.updated_at
FROM playlists p
LEFT JOIN playlist_tracks pt ON pt.playlist_id = p.id
WHERE p.user_id = $1::uuid
GROUP BY p.id
ORDER BY p.created_at DESC
`

type ListPlaylistsByUserRow struct {
	ID          string
	UserID      string
	Name        string
	Description pgtype.Text
	IsPublic    bool
	TrackCount  int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// Playlists de l'utilisateur, avec le nombre de pistes (LEFT JOIN pour compter 0
// sur une playlist vide). Triées par date de création décroissante.
func (q *Queries) ListPlaylistsByUser(ctx context.Context, userID pgtype.UUID) ([]ListPlaylistsByUserRow, error) {
	rows, err := q.db.Query(ctx, listPlaylistsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlaylistsByUserRow
	for rows.Next() {
		var i ListPlaylistsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.IsPublic,
			&i.TrackCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracksByUser = `-- name: ListTracksByUser :many
SELECT id::text AS id, title, artist, duration_s
FROM tracks
WHERE user_id = $1::uuid
ORDER BY created_at DESC
`

type ListTracksByUserRow struct {
	ID        string
	Title     string
	Artist    pgtype.Text
	DurationS pgtype.Int4
}

// Bibliothèque de pistes du demandeur : source du sélecteur « ajouter une
// piste » côté mobile. Les plus récentes d'abord.
func (q *Queries) ListTracksByUser(ctx context.Context, userID pgtype.UUID) ([]ListTracksByUserRow, error) {
	rows, err := q.db.Query(ctx, listTracksByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTracksByUserRow
	for rows.Next() {
		var i ListTracksByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Artist,
			&i.DurationS,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTrackFromPlaylist = `-- name: RemoveTrackFromPlaylist :one
DELETE FROM playlist_tracks
WHERE playlist_id = $1::uuid
  AND track_id = $2::uuid
RETURNING track_id::text AS track_id
`

type RemoveTrackFromPlaylistParams struct {
	PlaylistID pgtype.UUID
	TrackID    pgtype.UUID
}

// Retrait d'une piste. 0 ligne -> NotFound (piste absente de la playlist).
func (q *Queries) RemoveTrackFromPlaylist(ctx context.Context, arg RemoveTrackFromPlaylistParams) (string, error) {
	row := q.db.QueryRow(ctx, removeTrackFromPlaylist, arg.PlaylistID, arg.TrackID)
	var track_id string
	err := row.Scan(&track_id)
	return track_id, err
}

const reorderPlaylistTracks = `-- name: ReorderPlaylistTracks :execrows
UPDATE playlist_tracks pt
SET position = ord.pos
FROM (
    SELECT u.id AS track_id, (u.idx - 1)::int AS pos
    FROM unnest($2::uuid[]) WITH ORDINALITY AS u(id, idx)
) ord
WHERE pt.playlist_id = $1::uuid
  AND pt.track_id = ord.track_id
`

type ReorderPlaylistTracksParams struct {
	PlaylistID pgtype.UUID
	TrackIds   []pgtype.UUID
}

// Réécriture complète de l'ordre : la position de chaque piste vient de son rang
// dans le tableau fourni (WITH ORDINALITY). Le nombre de lignes touchées est
// comparé à l'effectif de la playlist par le repo -> un id étranger à la
// playlist fait échouer l'opération.
func (q *Queries) ReorderPlaylistTracks(ctx context.Context, arg ReorderPlaylistTracksParams) (int64, error) {
	result, err := q.db.Exec(ctx, reorderPlaylistTracks, arg.PlaylistID, arg.TrackIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resequencePlaylistTracks = `-- name: ResequencePlaylistTracks :exec
UPDATE playlist_tracks pt
SET position = ranked.rn - 1
FROM (
    SELECT track_id, ROW_NUMBER() OVER (ORDER BY position) AS rn
    FROM playlist_tracks
    WHERE playlist_id = $1::uuid
) ranked
WHERE pt.playlist_id = $1::uuid
  AND pt.track_id = ranked.track_id
  AND pt.position <> ranked.rn - 1
`

// Recompacte les positions en 0..n-1 après un retrait, pour qu'aucun trou ne
// subsiste (le réordonnancement suivant repartirait sur des index faussés).
func (q *Queries) ResequencePlaylistTracks(ctx context.Context, playlistID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resequencePlaylistTracks, playlistID)
	return err
}

const touchPlaylist = `-- name: TouchPlaylist :exec
UPDATE playlists SET updated_at = NOW() WHERE id = $1::uuid
`

// Met à jour updated_at de la playlist après une mutation de ses pistes.
func (q *Queries) TouchPlaylist(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchPlaylist, id)
	return err
}

const updatePlaylist = `-- name: UpdatePlaylist :one
UPDATE playlists
SET name = $1::text,
    description = $2::text,
    updated_at = NOW()
WHERE id = $3::uuid AND user_id = $4::uuid
RETURNING id::text AS id, user_id::text AS user_id, name, description, is_public,
          (SELECT COUNT(*) FROM playlist_tracks pt WHERE pt.playlist_id = playlists.id) AS track_count,
          created_at, updated_at
`

type UpdatePlaylistParams struct {
	Name        string
	Description pgtype.Text
	ID          pgtype.UUID
	UserID      pgtype.UUID
}

type UpdatePlaylistRow struct {
	ID          string
	UserID      string
	Name        string
	Description pgtype.Text
	IsPublic    bool
	TrackCount  int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// Renommage/description, restreint au propriétaire (id + user_id). 0 ligne -> le
// repo renvoie NotFound ; collision de nom -> 23505 -> 409.
func (q *Queries) UpdatePlaylist(ctx context.Context, arg UpdatePlaylistParams) (UpdatePlaylistRow, error) {
	row := q.db.QueryRow(ctx, updatePlaylist,
		arg.Name,
		arg.Description,
		arg.ID,
		arg.UserID,
	)
	var i UpdatePlaylistRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.TrackCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
