// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: playlists.sql

package playlistdb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlaylist = `-- name: CreatePlaylist :one
INSERT INTO playlists (user_id, name, description)
VALUES (
    $1::uuid,
    $2::text,
    $3::text
)
RETURNING id::text AS id, user_id::text AS user_id, name, description, is_public,
          0::bigint AS track_count, created_at, updated_at
`

type CreatePlaylistParams struct {
	UserID      pgtype.UUID
	Name        string
	Description pgtype.Text
}

type CreatePlaylistRow struct {
	ID          string
	UserID      string
	Name        string
	Description pgtype.Text
	IsPublic    bool
	TrackCount  int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// Création d'une playlist vide. La contrainte uq_playlists_user_name (000006)
// garantit l'unicité (user_id, name) : un doublon lève un 23505 -> 409 au repo.
func (q *Queries) CreatePlaylist(ctx context.Context, arg CreatePlaylistParams) (CreatePlaylistRow, error) {
	row := q.db.QueryRow(ctx, createPlaylist, arg.UserID, arg.Name, arg.Description)
	var i CreatePlaylistRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.TrackCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePlaylist = `-- name: DeletePlaylist :one
DELETE FROM playlists
WHERE id = $1::uuid AND user_id = $2::uuid
RETURNING id::text AS id
`

type DeletePlaylistParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

// Suppression définitive, restreinte au propriétaire. playlist_tracks est purgé
// en cascade (FK ON DELETE CASCADE). 0 ligne -> NotFound.
func (q *Queries) DeletePlaylist(ctx context.Context, arg DeletePlaylistParams) (string, error) {
	row := q.db.QueryRow(ctx, deletePlaylist, arg.ID, arg.UserID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getPlaylistByID = `-- name: GetPlaylistByID :one
SELECT p.id::text AS id, p.user_id::text AS user_id, p.name, p.description, p.is_public,
       COUNT(pt.track_id) AS track_count, p.created_at, p.updated_at
FROM playlists p
LEFT JOIN playlist_tracks pt ON pt.playlist_id = p.id
WHERE p.id = $1::uuid
GROUP BY p.id
`

type GetPlaylistByIDRow struct {
	ID          string
	UserID      string
	Name        string
	Description pgtype.Text
	IsPublic    bool
	TrackCount  int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// Une playlist par id (avec track_count). Le contrôle de propriété est fait par
// le service à partir du user_id renvoyé.
func (q *Queries) GetPlaylistByID(ctx context.Context, id pgtype.UUID) (GetPlaylistByIDRow, error) {
	row := q.db.QueryRow(ctx, getPlaylistByID, id)
	var i GetPlaylistByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.TrackCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlaylistTracks = `-- name: ListPlaylistTracks :many
SELECT t.id::text AS id, t.title, t.artist, t.duration_s, pt.position
FROM playlist_tracks pt
JOIN tracks t ON t.id = pt.track_id
WHERE pt.playlist_id = $1::uuid
ORDER BY pt.position
`

type ListPlaylistTracksRow struct {
	ID        string
	Title     string
	Artist    pgtype.Text
	DurationS pgtype.Int4
	Position  int32
}

// Pistes d'une playlist, ordonnées par position. artist et duration_s sont
// nullables (cf. table tracks). Le contrôle de propriété de la playlist est fait
// par le service en amont.
func (q *Queries) ListPlaylistTracks(ctx context.Context, playlistID pgtype.UUID) ([]ListPlaylistTracksRow, error) {
	rows, err := q.db.Query(ctx, listPlaylistTracks, playlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlaylistTracksRow
	for rows.Next() {
		var i ListPlaylistTracksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Artist,
			&i.DurationS,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaylistsByUser = `-- name: ListPlaylistsByUser :many
SELECT p.id::text AS id, p.user_id::text AS user_id, p.name, p.description, p.is_public,
       COUNT(pt.track_id) AS track_count, p.created_at, p.updated_at
FROM playlists p
LEFT JOIN playlist_tracks pt ON pt.playlist_id = p.id
WHERE p.user_id = $1::uuid
GROUP BY p.id
ORDER BY p.created_at DESC
`

type ListPlaylistsByUserRow struct {
	ID          string
	UserID      string
	Name        string
	Description pgtype.Text
	IsPublic    bool
	TrackCount  int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// Playlists de l'utilisateur, avec le nombre de pistes (LEFT JOIN pour compter 0
// sur une playlist vide). Triées par date de création décroissante.
func (q *Queries) ListPlaylistsByUser(ctx context.Context, userID pgtype.UUID) ([]ListPlaylistsByUserRow, error) {
	rows, err := q.db.Query(ctx, listPlaylistsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlaylistsByUserRow
	for rows.Next() {
		var i ListPlaylistsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.IsPublic,
			&i.TrackCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlaylist = `-- name: UpdatePlaylist :one
UPDATE playlists
SET name = $1::text,
    description = $2::text,
    updated_at = NOW()
WHERE id = $3::uuid AND user_id = $4::uuid
RETURNING id::text AS id, user_id::text AS user_id, name, description, is_public,
          (SELECT COUNT(*) FROM playlist_tracks pt WHERE pt.playlist_id = playlists.id) AS track_count,
          created_at, updated_at
`

type UpdatePlaylistParams struct {
	Name        string
	Description pgtype.Text
	ID          pgtype.UUID
	UserID      pgtype.UUID
}

type UpdatePlaylistRow struct {
	ID          string
	UserID      string
	Name        string
	Description pgtype.Text
	IsPublic    bool
	TrackCount  int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// Renommage/description, restreint au propriétaire (id + user_id). 0 ligne -> le
// repo renvoie NotFound ; collision de nom -> 23505 -> 409.
func (q *Queries) UpdatePlaylist(ctx context.Context, arg UpdatePlaylistParams) (UpdatePlaylistRow, error) {
	row := q.db.QueryRow(ctx, updatePlaylist,
		arg.Name,
		arg.Description,
		arg.ID,
		arg.UserID,
	)
	var i UpdatePlaylistRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.TrackCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
