// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package profilesdb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMe = `-- name: GetMe :one
SELECT u.id::text AS id, u.email, u.role, u.created_at,
       COALESCE(p.pseudo, u.username)          AS pseudo,
       COALESCE(p.bio, '')                     AS bio,
       p.avatar_url,
       COALESCE(p.theme, 'dark')               AS theme,
       COALESCE(p.notifications_enabled, true)  AS notifications_enabled,
       COALESCE(p.audio_quality, 'normal')      AS audio_quality
FROM users u
LEFT JOIN profiles p ON p.user_id = u.id
WHERE u.id = $1::uuid AND u.is_active = true
`

type GetMeRow struct {
	ID                   string
	Email                string
	Role                 string
	CreatedAt            time.Time
	Pseudo               string
	Bio                  string
	AvatarUrl            pgtype.Text
	Theme                string
	NotificationsEnabled bool
	AudioQuality         string
}

func (q *Queries) GetMe(ctx context.Context, id pgtype.UUID) (GetMeRow, error) {
	row := q.db.QueryRow(ctx, getMe, id)
	var i GetMeRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.Pseudo,
		&i.Bio,
		&i.AvatarUrl,
		&i.Theme,
		&i.NotificationsEnabled,
		&i.AudioQuality,
	)
	return i, err
}

const upsertProfile = `-- name: UpsertProfile :exec
INSERT INTO profiles (user_id, pseudo, bio, theme, notifications_enabled, audio_quality)
VALUES (
    $1::uuid,
    $2::text,
    $3::text,
    $4::text,
    $5::boolean,
    $6::text
)
ON CONFLICT (user_id) DO UPDATE
  SET pseudo = EXCLUDED.pseudo,
      bio = EXCLUDED.bio,
      theme = EXCLUDED.theme,
      notifications_enabled = EXCLUDED.notifications_enabled,
      audio_quality = EXCLUDED.audio_quality,
      updated_at = NOW()
`

type UpsertProfileParams struct {
	UserID               pgtype.UUID
	Pseudo               string
	Bio                  string
	Theme                string
	NotificationsEnabled bool
	AudioQuality         string
}

func (q *Queries) UpsertProfile(ctx context.Context, arg UpsertProfileParams) error {
	_, err := q.db.Exec(ctx, upsertProfile,
		arg.UserID,
		arg.Pseudo,
		arg.Bio,
		arg.Theme,
		arg.NotificationsEnabled,
		arg.AudioQuality,
	)
	return err
}
